/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/chiby.gltf 
Author: frannnny (https://sketchfab.com/frannnny)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chubbychibi-c25a8d1b69634b009686c8a349f98631
Title: Chubbychibi
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chiby.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.chubby_Skin_0.geometry} material={materials.Skin} />
          <mesh geometry={nodes.chubby_Skin_0_1.geometry} material={materials.Skin} />
          <mesh geometry={nodes.chubby_Skin_0_2.geometry} material={materials.Skin} />
          <mesh geometry={nodes.chubby_Skin_0_3.geometry} material={materials.Skin} />
          <mesh geometry={nodes.chubby_Skin_0_4.geometry} material={materials.Skin} />
          <mesh geometry={nodes.chubby_Skin_0_5.geometry} material={materials.Skin} />
          <mesh geometry={nodes.chubby_Skin_0_6.geometry} material={materials.Skin} />
          <mesh geometry={nodes.chubby_Skin_0_7.geometry} material={materials.Skin} />
          <mesh geometry={nodes.chubby_Skin_0_8.geometry} material={materials.Skin} />
          <mesh geometry={nodes.chubby_Skin_0_9.geometry} material={materials.Skin} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/chiby.gltf')
